on: [push]
jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -e
          rm -rf dist
          mkdir -p dist
          mkdir -p dist/kodi-radio-browser
          rsync -av . dist/kodi-radio-browser --exclude .git --exclude .github --exclude dist
          cd dist
          zip -r ../kodi-radio-browser.zip .
      - uses: actions/upload-artifact@v4
        with:
          path: |
            kodi-radio-browser.zip

